##Implementaion of the a Recursive Dynamic Programming algorithm to solve the Knapsack problem.

One recursive approach to solving this problem is a top down approach given by the below recursion.

$f_i^*(w) = \underset{x \in [0,1]}{max}\lbrace f^*_{i+1}(w) , [v_i + f^*_{i+1}(w-w_i)]$

- $i \in {1,2,3,4,.....N}$ each stage represents an item with a total of $N$ items
- $w \in {0,1,2,3,...W}$ total capacity of the knapsack is $W$
- $f_i^*(w)$ represents the maximum (additional) attainable value when going from current state $i$ to final state $N$, while making a series of policy decisions $x \in{[0,1]}$ 
- where $x = 1$ means the $i^{th}$ item is chosen. $x = 0$ means the $i^{th}$ item is not chosen.
- $v_i$ represents tha value of the $i^{th}$ item
- $w_i$ represents tha weight of the $i^{th}$ item

There is another recursive, and probably a more intuitive approach to solving this problem. The recursion is not expressed in terms of maximum "additional value" obtainable while going from $i^{th}$ stage to the $N^{th}$ stage. Instead, the recursion is expressed in terms of the optimal solutions for smaller subproblems.

The idea is as follows:

Let $S$ denote the set of items associated with the optimal solution. Let $G$ denote the set of all $N$ items. Then $S$ is the optimal solution of $G$. Let $w$ represent the available capacity of the knapsack at the time of deciding whether or not to choose item $N$. 

Now, Either $N \in S$ or $N \notin S$. If $N \notin S$ then $S$ is the optimal solution for a smaller problem with only the first $N-1$ items and available knapsack capacity $w$.

If $N \in S$, then $S - N$ is an optimal solution for a smaller problem with the first $N-1$ items and available capacity $w-w_N$

The above recursion can be written as follows:

$f_i^*(w) = \underset{x \in [0,1]}{max}\lbrace f^*_{i-1}(w) , [v_i + f^*_{i-1}(w-w_i)]$

Let us take a toy problem to implement the above recursion:

In [33]:
N = 4
W = 6
v = [3,2,4,4]
w = [4,3,2,3]

# let f denote the optimal solution values for smaller subproblems
# the stages will vary from 1 to N
# the states will vary from 0 to W
import numpy as np
f = np.zeros((5,7))
print f
for i in range(1,5):
    for x in range(7):
        #print i, x, 
        #print
        if w[i-1] > x:
            f[i, x] = f[(i-1),x]
        else:
            f[i, x] = max(f[(i-1),x], (v[i-1] + f[i-1, (x-w[i-1])]))

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [34]:
f

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  2.,  3.,  3.,  3.],
       [ 0.,  0.,  4.,  4.,  4.,  6.,  7.],
       [ 0.,  0.,  4.,  4.,  4.,  8.,  8.]])

In [47]:
f.transpose()

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  4.],
       [ 0.,  0.,  2.,  4.,  4.],
       [ 0.,  3.,  3.,  4.,  4.],
       [ 0.,  3.,  3.,  6.,  8.],
       [ 0.,  3.,  3.,  7.,  8.]])